<?php

namespace ContainerBEPYR2Z;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__TBVtrcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..TBVtrc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..TBVtrc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\HomeController::form' => ['privates', '.service_locator.UBfcEOe', 'get_ServiceLocator_UBfcEOeService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.12XOZIl', 'get_ServiceLocator_12XOZIlService', true],
            'App\\Controller\\HomeController::show' => ['privates', '.service_locator.tuUAVqB', 'get_ServiceLocator_TuUAVqBService', true],
            'App\\Controller\\HomeController::tricks' => ['privates', '.service_locator.12XOZIl', 'get_ServiceLocator_12XOZIlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\HomeController:form' => ['privates', '.service_locator.UBfcEOe', 'get_ServiceLocator_UBfcEOeService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.12XOZIl', 'get_ServiceLocator_12XOZIlService', true],
            'App\\Controller\\HomeController:show' => ['privates', '.service_locator.tuUAVqB', 'get_ServiceLocator_TuUAVqBService', true],
            'App\\Controller\\HomeController:tricks' => ['privates', '.service_locator.12XOZIl', 'get_ServiceLocator_12XOZIlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\HomeController::form' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::show' => '?',
            'App\\Controller\\HomeController::tricks' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\HomeController:form' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:show' => '?',
            'App\\Controller\\HomeController:tricks' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
