<?php

namespace ContainerA9iecxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FgK5HHQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fgK5HHQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fgK5HHQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored.rdcTQ8n', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::show()": the $article argument is type-hinted with the non-existent class or interface: "App\\Entity\\Article".'],
        ], [
            'article' => '?',
        ]);
    }
}
