<?php

namespace ContainerA9iecxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RdcTQ8nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.rdcTQ8n' shared service.
     *
     * @return \App\Entity\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\HomeController::show()": the $article argument is type-hinted with the non-existent class or interface: "App\\Entity\\Article".');
    }
}
