<?php

namespace Container0XxZZxt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__NOHw1EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..nOHw1E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..nOHw1E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\HomeController::articles' => ['privates', '.service_locator.fpD7nIw', 'get_ServiceLocator_FpD7nIwService', true],
            'App\\Controller\\HomeController::form' => ['privates', '.service_locator.Lu.fzLE', 'get_ServiceLocator_Lu_FzLEService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.fpD7nIw', 'get_ServiceLocator_FpD7nIwService', true],
            'App\\Controller\\HomeController::show' => ['privates', '.service_locator.XqCCpgA', 'get_ServiceLocator_XqCCpgAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\HomeController:articles' => ['privates', '.service_locator.fpD7nIw', 'get_ServiceLocator_FpD7nIwService', true],
            'App\\Controller\\HomeController:form' => ['privates', '.service_locator.Lu.fzLE', 'get_ServiceLocator_Lu_FzLEService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.fpD7nIw', 'get_ServiceLocator_FpD7nIwService', true],
            'App\\Controller\\HomeController:show' => ['privates', '.service_locator.XqCCpgA', 'get_ServiceLocator_XqCCpgAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\HomeController::articles' => '?',
            'App\\Controller\\HomeController::form' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\HomeController:articles' => '?',
            'App\\Controller\\HomeController:form' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
