<?php

namespace ContainerLBLpOm0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9TC_F1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9TC.F1_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9TC.F1_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comment' => ['privates', '.errored..service_locator.9TC.F1_.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.9TC.F1_": it needs an instance of "App\\Entity\\Comment" but this type has been excluded in "config/services.yaml".'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'trick' => ['privates', '.errored..service_locator.9TC.F1_.App\\Entity\\Trick', NULL, 'Cannot autowire service ".service_locator.9TC.F1_": it needs an instance of "App\\Entity\\Trick" but this type has been excluded in "config/services.yaml".'],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'manager' => '?',
            'trick' => 'App\\Entity\\Trick',
        ]);
    }
}
