<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCQuJxb7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCQuJxb7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCQuJxb7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCQuJxb7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCQuJxb7\App_KernelDevDebugContainer([
    'container.build_hash' => 'CQuJxb7',
    'container.build_id' => '90917e8a',
    'container.build_time' => 1708547817,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCQuJxb7');
