<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9VkfDeX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9VkfDeX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9VkfDeX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9VkfDeX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9VkfDeX\App_KernelDevDebugContainer([
    'container.build_hash' => '9VkfDeX',
    'container.build_id' => '8959f312',
    'container.build_time' => 1708345649,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9VkfDeX');
