<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0XxZZxt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0XxZZxt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0XxZZxt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0XxZZxt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0XxZZxt\App_KernelDevDebugContainer([
    'container.build_hash' => '0XxZZxt',
    'container.build_id' => '3993bb15',
    'container.build_time' => 1705930394,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0XxZZxt');
